export interface PastStatsPlayerStatistics {
    first_name: string,
    last_name: string,
    points: number,
    minutes: string,
    rebounds: number,
    assists: number, 
    field_goals_made: number,
    field_goals_att: number,
    three_points_made: number,
    three_points_att: number,
    free_throws_made: number,
    free_throws_att: number,
    steals: number,
    blocks: number,
    turnovers: number, 
    personal_fouls: number,
    pls_min: number,
    starter: boolean,
}